### ISSUE TITLE
Type definition file missed

### ISSUE THREAD

**Issue by pucelle** [ExtendScript/extendscript-es6-shim#9]
I can see there are some `*.d.ts` files in `extendscript-es5-shim`, but not this one. Seems been forgot.
Otherwise, Is there a plan to support ES2017 and the following?

**Comment by ff6347** [comment]
All PRs are welcome. There is currently none actively maintaining this. More like people stopping by and fixing things they need. 

There are some projects which do typescript to extendscript transpilation. 

E.g. https://github.com/ten-A/Types-for-Adobe

**Comment by ff6347** [comment]
https://github.com/Inventsable/scriptopia

**Comment by ff6347** [comment]
https://github.com/pravdomil/Types-for-Adobe

☝🏽

These links should get you started. As I said PRs are welcome

**Comment by pucelle** [comment]
Ok,Thanks very much.
